<?php

namespace CoreBundle\Repository;

/**
 * QuestionsCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionsCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
