<?php

namespace CoreBundle\Repository;

/**
 * QuestiontypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestiontypeRepository extends \Doctrine\ORM\EntityRepository
{
}
