<?php

namespace CoreBundle\Repository;

/**
 * SurveyCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SurveyCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
