<?php

namespace CoreBundle\Repository;

/**
 * TempAccessRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TempAccessRepository extends \Doctrine\ORM\EntityRepository
{
}
